# =============================================================================
# File        : automerge.yml
# Author      : yukimemi
# Last Change : 2024/07/13 22:53:33.
# =============================================================================

name: automerge

on:
  workflow_dispatch:
  pull_request:
  check_suite:
    types: [completed]
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check Deno
        run: deno task ci

      - name: automerge
        id: automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
